// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PublicDbContext))]
    [Migration("20250604013209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CategoriesCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("categories_catalogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogOptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("catalogoptions_id");

                    b.Property<int>("CategoriesCatalogId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriesOptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("categoriesoptions_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 6, 4, 1, 32, 8, 290, DateTimeKind.Utc).AddTicks(5267));

                    b.Property<int>("OptionsResponseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 6, 4, 1, 32, 8, 294, DateTimeKind.Utc).AddTicks(4240));

                    b.HasKey("Id");

                    b.HasIndex("CategoriesOptionsId");

                    b.HasIndex("OptionsResponseId");

                    b.ToTable("category_options", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Chapters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chapter_number");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chapter_title");

                    b.Property<string>("ComponentHtml")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("componenthtml");

                    b.Property<string>("ComponentReact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("componentreact");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OptionQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesCatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentOptionres")
                        .HasColumnType("text")
                        .HasColumnName("comment_optionres");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 6, 4, 1, 32, 8, 302, DateTimeKind.Utc).AddTicks(4100));

                    b.Property<string>("NumberOption")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number_option");

                    b.Property<int>("OptionCatalogId")
                        .HasColumnType("integer")
                        .HasColumnName("optioncatalog_id");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer")
                        .HasColumnName("option_id");

                    b.Property<int>("OptionQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("optionquestion_id");

                    b.Property<int>("OptionsResponseId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SubquestionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 6, 4, 1, 32, 8, 302, DateTimeKind.Utc).AddTicks(4810));

                    b.HasKey("Id");

                    b.HasIndex("CategoriesCatalogId");

                    b.HasIndex("OptionsResponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubquestionId");

                    b.ToTable("option_questions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OptionsResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OptionText")
                        .HasColumnType("text")
                        .HasColumnName("option_text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("options_responses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentQuestion")
                        .HasColumnType("text")
                        .HasColumnName("comment_question");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QuestionNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("question_number");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("ResponseType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("response_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SubQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentSubQuestion")
                        .HasColumnType("text")
                        .HasColumnName("comment_subquestion");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("SubquestionNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("subquestion_number");

                    b.Property<string>("SubquestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subquestion_text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("sub_questions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SumaryOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_number");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<string>("Valuerta")
                        .HasColumnType("text")
                        .HasColumnName("valuerta");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("sumary_options", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Surveys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentHtml")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("componenthtml");

                    b.Property<string>("ComponentReact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("componentreact");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryOptions", b =>
                {
                    b.HasOne("Domain.Entities.CategoriesCatalog", "CategoriesCatalog")
                        .WithMany("CategoryOptions")
                        .HasForeignKey("CategoriesOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OptionsResponse", "OptionsResponse")
                        .WithMany("CategoryOptions")
                        .HasForeignKey("OptionsResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesCatalog");

                    b.Navigation("OptionsResponse");
                });

            modelBuilder.Entity("Domain.Entities.Chapters", b =>
                {
                    b.HasOne("Domain.Entities.Surveys", "Surveys")
                        .WithMany("Chapters")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("Domain.Entities.OptionQuestions", b =>
                {
                    b.HasOne("Domain.Entities.CategoriesCatalog", "CategoriesCatalog")
                        .WithMany("OptionQuestions")
                        .HasForeignKey("CategoriesCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.OptionsResponse", "OptionsResponse")
                        .WithMany("OptionQuestions")
                        .HasForeignKey("OptionsResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Questions", "Questions")
                        .WithMany("OptionQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubQuestions", "SubQuestions")
                        .WithMany("OptionQuestions")
                        .HasForeignKey("SubquestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriesCatalog");

                    b.Navigation("OptionsResponse");

                    b.Navigation("Questions");

                    b.Navigation("SubQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Questions", b =>
                {
                    b.HasOne("Domain.Entities.Chapters", "Chapters")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Domain.Entities.SubQuestions", b =>
                {
                    b.HasOne("Domain.Entities.Questions", "Questions")
                        .WithMany("SubQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.SumaryOptions", b =>
                {
                    b.HasOne("Domain.Entities.Questions", "Questions")
                        .WithMany("SumaryOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Surveys", "Surveys")
                        .WithMany("SumaryOptions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("Domain.Entities.CategoriesCatalog", b =>
                {
                    b.Navigation("CategoryOptions");

                    b.Navigation("OptionQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Chapters", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.OptionsResponse", b =>
                {
                    b.Navigation("CategoryOptions");

                    b.Navigation("OptionQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Questions", b =>
                {
                    b.Navigation("OptionQuestions");

                    b.Navigation("SubQuestions");

                    b.Navigation("SumaryOptions");
                });

            modelBuilder.Entity("Domain.Entities.SubQuestions", b =>
                {
                    b.Navigation("OptionQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Surveys", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("SumaryOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
